services:
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports:
            - "2181:2181"
        networks:
            - micro_net

    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:6.2.1
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
            - "29092:29092"
        networks:
            - micro_net

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - node.name=elasticsearch
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - micro_net

    postgres:
        image: postgres:14.0
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: kong
        ports:
            - "5440:5432"
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - ./db-data/kong_db_data:/var/lib/postgresql/data
        networks:
            - micro_net

    catalog_db_server:
        container_name: catalog_db_server
        image: postgres:14.0
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: catalog_db
            POSTGRES_PASSWORD: catalog_db_password
            POSTGRES_DB: catalog_service
        volumes:
            - ./db-data/catalog_db_server/:/var/lib/postgresql/data
        networks:
            - micro_net

    cargo_db_server:
        container_name: cargo_db_server
        image: postgres:14.0
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: cargo_db
            POSTGRES_PASSWORD: cargo_db_password
            POSTGRES_DB: cargo_service
        volumes:
            - ./db-data/cargo_db_server/:/var/lib/postgresql/data
        networks:
            - micro_net

    order_db_server:
        container_name: order_db_server
        image: postgres:14.0
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: order_db
            POSTGRES_PASSWORD: order_db_password
            POSTGRES_DB: order_service
        volumes:
            - ./db-data/order_db_server/:/var/lib/postgresql/data
        networks:
            - micro_net

    user_db_server:
        container_name: user_db_server
        image: postgres:14.0
        ports:
            - "5442:5432"
        environment:
            POSTGRES_USER: user_db
            POSTGRES_PASSWORD: user_db_password
            POSTGRES_DB: user_service
        volumes:
            - ./db-data/user_db_server/:/var/lib/postgresql/data
        networks:
            - micro_net

    catalog_service:
        container_name: catalog_service
        image: i_catalog_service
        build:
            context: ./catalog_service
            dockerfile: Dockerfile
        env_file:
            - ./catalog_service/.env
        depends_on:
            - kafka
            - elasticsearch
            - catalog_db_server
        restart: unless-stopped
        networks:
            - micro_net

    order_service:
        container_name: order_service
        image: i_order_service
        build:
            context: ./order_service
            dockerfile: Dockerfile
        env_file:
            - ./order_service/.env
        depends_on:
            - kafka
            - order_db_server
        restart: unless-stopped
        networks:
            - micro_net

    user_service:
        container_name: user_service
        image: i_user_service
        build:
            context: ./user_service
            dockerfile: Dockerfile
        env_file:
            - ./user_service/.env
        depends_on:
            - user_db_server
        restart: unless-stopped
        networks:
            - micro_net

    payment_service:
        container_name: payment_service
        image: i_payment_service
        build:
            context: ./payment_service
            dockerfile: Dockerfile
        env_file:
            - ./payment_service/.env
        environment:
            - APP_PORT=9003
            - ORDER_SERVICE_BASE_URL=http://order_service:9002
            - AUTH_SERVICE_BASE_URL=http://user_service:9000
            - CLIENT_ID=order-service
            - GROUP_ID=order-service-group
            - BROKER_1=kafka:9092
        restart: unless-stopped
        networks:
            - micro_net

    payment_frontend:
        container_name: payment_frontend
        image: i_payment_frontend
        build:
            context: ./payment_frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - micro_net

    email_service:
        container_name: email_service
        image: i_email_service
        build:
            context: ./email_service
            dockerfile: Dockerfile
        env_file:
            - ./email_service/.env
        depends_on:
            - kafka
        restart: unless-stopped
        networks:
            - micro_net

    cargo_service:
        container_name: cargo_service
        image: i_cargo_service
        build:
            context: ./cargo_service
            dockerfile: Dockerfile
        env_file:
            - ./cargo_service/.env
        depends_on:
            - kafka
            - cargo_db_server
        restart: unless-stopped
        networks:
            - micro_net

    kong-migrations:
        image: kong/kong-gateway:latest
        container_name: kong-migrations
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: postgres
            KONG_PG_USER: postgres
            KONG_PG_PASSWORD: postgres
            KONG_PG_DATABASE: kong
        command: kong migrations bootstrap
        restart: on-failure
        depends_on:
            - postgres
        networks:
            - micro_net

    kong:
        container_name: kong
        image: kong/kong-gateway:latest
        ports:
            - "80:80" # Proxy trafiği buradan girecek
            - "443:443"
            - "8001:8001" # Admin API (ayarları görmek için)
            - "8444:8444"
            - "8002:8002"
            - "8445:8445"
        environment:
            KONG_DATABASE: "off"
            KONG_PG_HOST: postgres
            KONG_PG_USER: postgres
            KONG_PG_PASSWORD: postgres
            KONG_PG_DATABASE: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_PROXY_LISTEN: "0.0.0.0:80 reuseport, 0.0.0.0:443 ssl reuseport"
            KONG_ADMIN_LISTEN: "0.0.0.0:8001 reuseport, 0.0.0.0:8444 ssl"
            KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
        depends_on:
            - kong-migrations
        volumes:
            - ./kong.yml:/etc/kong/kong.yml
        networks:
            - micro_net
        restart: always

volumes:
    esdata:
        driver: local
    kong_db_data:

networks:
    micro_net:
        driver: bridge
